greenmemory: fix windows error
This patch fixes error in the windows compilation because the header
functional is not present.
Error C2039: 'less_equal' : is not a member of 'std'

Signed-off-by: Alexis Semren <alexis.semren@greensocs.com>